---

- name: FUN repositories
  hosts: 127.0.0.1
  connection: local
  vars:
    version: "{{ ansible_env.FUN_RELEASE | default('master') }}"

  tasks:
    - debug: msg="Fetching version {{ version }} of FUN repositories"
    - name: Create 'themes' directory
      file: state=directory path={{ root_dir }}/themes
    - name: Create 'themes/fun' directory
      file: state=directory path={{ root_dir }}/themes/fun

    - name: Checkout fun-apps repository
      git: repo=https://github.com/openfun/fun-apps dest={{ root_dir }}/fun-apps/ version={{ version }}
    # TODO this does not work yet because the repository is private
    #- name: Checkout fun-config repository
      #git: repo=git://github.com/openfun/fun-config dest={{ root_dir }}/fun-config/ version={{ version }}
    - name: Checkout edx-theme repository
      git: repo=https://github.com/openfun/edx-theme dest={{ root_dir }}/themes/fun version={{ version }}
    - name: Checkout edx-plaftorm repository
      git: repo=https://github.com/openfun/edx-platform dest={{ root_dir }}/edx-platform version=fun/release-{{ version }}
